k8s_config:
- manifest_path: /manifests
  cluster_info:
    cluster_id: 15e17bf0-2068-5c9d-8dec-f490aa06102d
    cluster_name: David Dymko's cluster
- manifest_path: /manifests
  cluster_info:
    cluster_id: 15e17bf0-2068-5c9d-8dec-f490aa06102d
    cluster_name: David Dymko's cluster
